atlantis-url: "http://atlantis.raj.ninja"
automerge: true
data-dir: "/atlantis"
log-level: "info"
repo-config: "/repos.yaml"
repo-whitelist: "github.com/msfidelis/atlantis-*"
gh-user: "msfidelis"
gh-token: "1bfdc9796f94226f29eb090a938240e4a7349186"